---
# defaults file for caddy
caddy_user: root
caddy_container_name: caddy
caddy_container_image: docker.io/library/caddy
# caddy_container_image: 0b36305c4573
caddy_www_root: /srv/caddy/
caddy_root: /var/local/caddy
caddy_volumes:
  - config
  - data
  - cert
caddy_container_volumes:
  - "{{ caddy_www_root }}:/srv:Z"
  - "{{ (caddy_root, 'config') | path_join }}:/config:Z"
  - "{{ (caddy_root, 'Caddyfile') | path_join }}:/etc/caddy/Caddyfile:Z"
  - "{{ (caddy_root, 'data') | path_join }}:/data:Z"
  - "{{ (caddy_root, 'cert') | path_join }}:/cert:Z"
# caddy_container_volumes:
#   - "{{ www_root }}:/srv:Z"
#   - "{{ (caddy_root, 'config') | path_join }}:/caddy/config:Z"
#   - "{{ (caddy_root, 'Caddyfile') | path_join }}:/caddy/Caddyfile:Z"
#   - "{{ (caddy_root, 'data') | path_join }}:/caddy/data:Z"
#   - "{{ (caddy_root, 'cert') | path_join }}:/caddy/cert:Z"
caddy_container_ports:
  - '80:80'
  - '443:443'
# caddy_container_ports:
#   - '80:8080'
#   - '443:8443'
caddy_svc: container-caddy.service
caddy_svc_dir: '/etc/systemd/system'
caddy_cert_src: '/etc/pki/tls/certs/oconnor.dev-fullchain.crt'
caddy_key_src: '/etc/pki/tls/private/oconnor.dev.key'
caddy_cert_dest: "{{ (caddy_root, 'cert', 'oconnor.dev.crt') | path_join }}"
caddy_key_dest: "{{ (caddy_root, 'cert', 'oconnor.dev.key') | path_join }}"
caddy_config_file:
  src: "{{ (caddy_fullchain.stat.exists) | ternary('Caddyfile', 'Caddyfile_http') }}"
  dest: "{{ (caddy_root, 'Caddyfile') | path_join }}"
