---
- name: configure the site
  hosts: webservers
  tasks:
    - name: deploy
      include_role:
        name: deploy

    - name: security
      include_role:
        name: security

    - name: caddy
      include_role:
        name: caddy
