---
# tasks file for deploy
- name: set system timezone
  timezone:
    name: "{{ deploy_timezone }}"
    hwclock: UTC

- name: install packages
  include_tasks: packages.yml

- name: disable unneeded services
  service:
    name: mcelog
    state: stopped
    enabled: false
