---
- name: Configuring oconnor.dev
  hosts: webservers
  tasks:
    - name: enforce SELINUX security policy
      selinux:
        policy: targeted
        state: enforcing

    - name: set system timezone
      timezone:
        name: America/New_York
        hwclock: UTC

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: ensure packages are installed
      yum:
        name:
          - '@container-tools'
          - 'firewalld'
          - 'git'
          - 'openssl'
        state: latest

    - name: add ssh public key for user
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: add hardened ssh config
      copy:
        dest: /etc/ssh/sshd_config
        src: ./sshd_config
        owner: root
        group: root
        mode: 0600
      notify: reload ssh

    # - name: ensure firewalld service is enabled and running
    #   service:
    #     name: 'firewalld'
    #     enabled: true
    #     state: started

    # - name: permit traffic in default zone for http/https services
    #   firewalld:
    #     service: "{{ item }}"
    #     state: enabled
    #     permanent: true
    #     immediate: true
    #   loop:
    #     - http
    #     - https

  handlers:
    - name: reload ssh
      service:
        name: 'sshd'
        state: reloaded
