---
# defaults file for caddy
caddy_user: root
caddy_container_name: caddy
caddy_container_image: docker.io/library/caddy
www_root: /srv/caddy/
caddy_root: /var/local/caddy
caddy_volumes:
  - config
  - data
  - cert
caddy_container_volumes:
  - "{{ www_root }}:/srv:Z"
  - "{{ (caddy_root, 'config') | path_join }}:/config:Z"
  - "{{ (caddy_root, 'Caddyfile') | path_join }}:/etc/caddy/Caddyfile:Z"
  - "{{ (caddy_root, 'data') | path_join }}:/data:Z"
  - "{{ (caddy_root, 'cert') | path_join }}:/cert:Z"
caddy_container_ports:
  - '80:80'
  - '443:443'
caddy_svc: container-caddy.service
caddy_svc_dir: '/etc/systemd/system'
cert_path: '/etc/pki/tls/certs/oconnor.dev.crt'
key_path: '/etc/pki/tls/private/oconnor.dev.key'
caddy_cert_path: "{{ (caddy_root, 'cert', 'oconnor.dev.crt') | path_join }}"
caddy_key_path: "{{ (caddy_root, 'cert', 'oconnor.dev.key') | path_join }}"
caddy_config_file:
  src: "{{ (public_cert.stat.exists) | ternary('Caddyfile', 'Caddyfile_http') }}"
  dest: "{{ (caddy_root, 'Caddyfile') | path_join }}"
